# Ingress (edges) for all platform UIs.
ingress-edge:
  ingresses:
    - name: platform
      domain: pontiki.app
      issuer: letsencrypt-staging # todo: switch to letsencrypt-prod once testing is done.
      hosts:
        - subdomain: argocd
          targetNamespace: argocd
          targetService: argocd-server
          targetPort: 80
        - subdomain: grafana
          targetNamespace: monitoring
          targetService: grafana
          targetPort: 80
        - subdomain: vmui
          targetNamespace: monitoring
          targetService: vmsingle-victoria-metrics-k8s-stack
          targetPort: 8428
        - subdomain: vlogs
          targetNamespace: monitoring
          targetService: vlsingle-victoria-logs
          targetPort: 9428
