---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp
  namespace: monitoring
spec:
  encryptedData:
    password: AgDfsGtMPlygstuHEpyeWDWzkcZoQcnBvWDt0rqu+ibJPt8x75BjYb4PkasKQTdQnBJqh2GNLyt//uVlZCk0hxGSAQ+61m8+LYGIxVSE0fg/EVkW62erPPAOcI6o6EyDsRCORMuYyT+KwaSe/YZv09QzcUyNvl0JCguPd6rat5cWGIfCYaNw3OmEf30EKxIpkg2vr1L7KoA9AodeyImeLUZAbLVJvOxL1aydoSqmok66kFLRCMTNNvNy3qRImHpIjR0Vh6pPRWqUpf9dTf29tusmpd1qeqMRqR/T6/YbWk45vsKj1unkAVsr2hZxwHbRNC9aDj9tuC0DP1PcT2U7rtQn60KCzovN8RLPdLzcHP78arbVg90uMWrlKIriRTi1h9R9VyNze2fUDwqh/m/tKCL8eNpjP80p2pvcHHA3SKc47+IVWbbZY9T7ftDpOHDGc/le6lgWahllpRdYsGuaqeBd4JxV88EVvBjiDsaE8QeTxRiHNzL9kH7slqwjZf0jeAbkhswHXxT9vaFJ1DYnkFgcDhYUTm8gfknC+28Yo9B7mk9T6mbFzjboM8qkr+VCQJ7z3n3y29pcle3U8pJBxZooAsmieDk/uhCapr37maYQvJ0L9GZCMFjE3V4PkefPshV3NRtNNMlS8kjuYNj5q4Q/1YQMkrmZ+z9bew12Fasa+oUQkiXlu6z2rU7z+L8jd3a7iDv2+utuQDSaQN3JJxKRnoXe
  template:
    metadata:
      name: grafana-smtp
      namespace: monitoring
