---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp
  namespace: monitoring
spec:
  encryptedData:
    password: AgBkvO6oFh4MuzyTvE505zLGfIZ+QV1f4LR7FFyh390Ehr+jtc0FLKOQVd/kC6/3/KeLqHPxWkVSGzdqtDJ/2zIcQTEnWPRgos9w4ngEpCs/yNrTAKQt5ivYpOUv0L/3k8JGrAGDJhNZJMKAbOSwO3Xl5L+NYD0cwUmqY3EUqDUuB0ShOWu8ikDmwgeMaKoa6pVB2KO5GSeXoJ4zBl7Ko3/0HMp4eCXIqpHqC1kiNO1mGF1Fc0kxd3T8kk+75JxgK5KFwtS8aTEZP0xDC9lDujsgLOO+3CU0RVnDPl3zO9LUJqjMHbvF676dGhf+JwoP3R2x+yA59c2/FSt18Vu/YIpaLcSmYaNAsRK/K2V+2+TuwOwjYNnVtIvIwmg0IR6nBFIJnfN/Zy/PXPrcisWjWjv8c/BF2gJIoytU9EN0ZHVnxkTTpnPDYlQsYUE3K7CEt7tnfStiPQkJelefyJ0yTdML/2Em+FNSXNc8pPM8nPmjYVHvbUH4UUAkC7SOZS7Kk/NIQ+E3u5rYkR2f7omYD0R8lO03JSdgBD4v2aTjv0PWbngFW8ZswgD241/xZXP0v6barJME+8k/ky4S99qE9eIHRIda2DxBmLszCWqm2hifLPWmOWi4zcf2uTY9ZZyZaaIii1p3kuR/Mnu88GTA4JJ3H/LnF8cr88etNyaPKYGSKh0y8Ol6KwDYwFy7W0MeMr0IZXR+t3wKigk8+Ei4K4JH29xz
  template:
    metadata:
      name: grafana-smtp
      namespace: monitoring
