---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp
  namespace: monitoring
spec:
  encryptedData:
    password: AgCVyBKeCjfWqDHG7Qo4+DPmxC8kCg8Vd5GhvkQnFnIRmhdUWRw0Uq4AhCJnaUeRKRreFSN69JHnnMaE/sYm0MoD2KpSE+4UZP0T+fCgYfKh3KDUMeJv1kKJ/e3VHTrpxsLkZ7wxhFeMSRrGlkn8DhuWIQoi98TKNlZhMtiB98LtN0mphuRra1wAbBPmIb1gjETbsuckQprXGCfoEur7BVpulE4d5wIRjjZu11HWIW3hBUTikX+7KwdsiFpIynHepHBxpfznFdN4Q9Vhwxm1cQwPwMcuMgxVHGf84SWqZYIoozV3RUXmh6fTgcqksgkguVeL2bpLO5a8rf/bco0DdoxiTDsLch2FDDuPue3mNhd+V3dNXjCZKz/LrxFLeJyR6q8o/s/rW3hc//xq6MBuqtlZRgyV2FH6m5zNnsuxGAuNUR879oZSvGGYCQWPwHDa3MDOU7PnZodq9NQCluadTN89ru/qe5JzVYk0yK9KrPpavMVWstErr8NsUL6HjirkxBXEjInK7mFBDf/LC0GtmY4Z+zYIu+wkJ/nLbhtYHS1y6jc2RTXBuSaQo9XSFNRGSKgv5+fXrtQn2sKsM/Pv9hGTz8c70ts7wnqcDeFlm+bHf+kOxEihPnLYAzH12fsAHCFGRV2EmKf+wQ+3qv6AQnecWUsyyO3xAxB9iuFSTIzusK8xbCCr+yPv1WoeblOoSs6fKlcx6GMymzVRoZQAKwdOxfHX
  template:
    metadata:
      name: grafana-smtp
      namespace: monitoring
