---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vm-backup-s3
  namespace: monitoring
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBH6APuKwX3m4R7/uZXcSquwynA9//HZhzefAJKm+4RIv64vJ8gVQw8yfpuNGQANlzCFmA6nUFVqTg9P/BmwYnhKq/HBVCSmJrkjmKGFkk49i0NgbxaY2oWmjORZsK+Tn+UC+aJsgjQA/taInUEz3LpYDj+iOEeeME1+3zA6GqjGnD7qpySTMvXFyGiCZFLfLdShS3SNGiOgUBtBykwm/TGNaOcrXGAzDYvy+FklVy1db382GwZU61sMkO/2f530LUeI3g2A+cySsFP8BbuC/s5sqb3rNQDzG+YiYBjKR84u131dQg2rn7ez+Adtn7z16zvTUxxiyoIcO4R1Y16EnTruJ/tatFhtDg3VmO0bx4b5p5WVU09y2/MQ+DA4SSzd2pwO9o+cuMz66Dniill26BhrBD8MnIhAo1X+2p2IAaNhyZTZ7tVnJaFI2bdih9BsYuktGLzy+0PPUKuXbrwIG/YKYgKTUu3Z8nxuxOGGVdkHKjAt3bC/0vgQAffhhxpoRxPzTTrqMnHjrm9qim56SBcJnCb9gYAM9CIa6gj7lI5/5oPXWM7JHdZSHeuyOrfVac7Ge9MeDstFReRY4aaDlgAZUYu/DVoArKQOz2bzAHPq51fj/rsr2xQ0Z4jftSKaP/BOJ0EajiW1IxYnzxns6ZgSdeEb/R5vIRa3Jlkc4a09VeC5+zNvmqLqSJ5i8EsNGPlOKZ56OgfSOLklfGz7RpC7SK3dw==
    AWS_SECRET_ACCESS_KEY: AgBmzpKUUwS2nlhG3fpm+uQZnrjF8aFx08RitK49+6ajuEzHlfbTH8iwYL1jiEI+lQgasB1i3WtKKm79WQQ4MFyLFilgUfBEcBccgtiu9Cc/JbT6nOL+GK2yPHxOkfinkeUd2QMiPnJxoj1uP8p9UzbYDZSAi0+PZcmV70mjxmGuw/hkiZvX2cSyQ5rmEcFX2RcVLqTgn1aDDPLglMJhqs5p/p706wGoLRvqWjEJSIhWBkRt7CnDfccC8SKfe56itccK109QqZ24OgzkHbDY+4EB3rznucxdg/FpMppwOaXJPIo2KXdEdeReR0192yl3V8HM722E2ggfFBhTAwazlhqkKN/Jvo8dM7yv4/nKv3gSngL4PBReB6tvVrRLbjOMpnIWyNBtizfDXx0LoR+baCNfvmW0x22j11JjAi655F15UVL1lWPrFqw25bEQH3+5YZ9/uaGWO5wcX5lVbnRQN+X7+iDzjVjY/Ayu0mnwIlUYXi0iLlDytzIv9y1Km3s2vg2QXpJK+HDkomlSFWq6mjQA3eeeBg7dcwqsDZgr8wLyjMIuCrZLBrcMnrE9AL3AcTO7jOwryM4l3HUpQJQvyUb0kXL2Gfl75UVHK/jnayqzEXTOHuj6sqCXOx6lmD/wcUtO5n2sTrBMyHBvuYOLgTUtEbckN9L35JCC8/w9WpAsqBU60HJo+QK0ONo0Q9w/6P4Oi+jjUwoscf+8ZEV0lMBUfOkxgV3vv/RClOG4zzX5i9/PDHwIop9R
  template:
    metadata:
      name: vm-backup-s3
      namespace: monitoring
