---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vm-backup-s3
  namespace: monitoring
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAU5M6zXhvdI+hoXKyEPFk/1mrmvAO7lUkJK0bsXBXfvolM/HlKoywS0ukkWByE71blgc1M5PkRlJoK2vuu9Dt83WNnEmdLuMzSOSJfzK9ylk2n60W52AYIUjo24SgtJaF3XPr1oLK4S+ORL7Th60VD1cHKUeERBTezSaJATQlfUjQA9pdQkwCfJFFhkc01jlOYjff0/iQ3OzZX71A9QJAL0TJECj3Cg1ZssvjOq2/VE7IQG4KZH0BWu4oKBlFMffjF8oi6GNvtazDqwth77i28a3vEQkXFNgFuUf8WuorTcQsrVZ5dJkP5J5sQ9xwzk5H8MvH+lReDaNviOeWvQpM1Lsimy1cjxe5GQ83EO41ncoX2JosrQIA7J+HVHwWELC6msKmvm9sDBGQhHsS3eKHgxIvRfG9uvCJRaqZjyW6w7Spqp/9przcDDqw5u/i5Pv5/JlCO7a+mA7HOmqBjJEJYiy6KLNy6vhwopoIIXtxr6OTcKGQcxghg3z0/5eHTVIcTYGw2nosNQ6vsPHu0w/ceQNZB8nsuG14FBwj0nfS3xhgU8MvEJnaP5NP+kNmdZ29POHqnZJ1OkMJnkpqlPsxPlQEST46TMeF+gERfDfnZj7uq+QN3VlpNg60U7GmbA+wNsrOoZoxJ8i02gwhHfC4nrk9YCJ4M0hlCmwPmWYRGOoxMX2mNcuajhZZ9a0DquNkMe1iTQtOlt1DdghrshW3dmzKknA==
    AWS_SECRET_ACCESS_KEY: AgAeZCu9ISCbCLxvtoEtcIbFakjp3xkT6XATSzDO3qVQRU4uhios/9FyrxgCDVEFnlvnXSWjJRENwpzCDFKiv0sR6FQKoQk75D3AeUesVlk5JofD2HeIIQS500k+l9Dafn2ihWqCxVhf8+FiBX3Od0nDd5citGcxrn+0BpIbrIx8bFxAiizIQ/YZ15uZpewl8LEh97KxJhXxCv9SdFJm1A1RfnMyxuQp5KL/CHdsaL8i5iY252mBvc15U8oCTrCUXQm1K+ca/Ef1m5GAonMCceoq6PndWz04ibRD+aA4/i0Zr+zyGAGxaRnJQw3WlUYWnbvLf78JsD89JMOjiv8/d2BLyC7FErcE3MclOsYQMJ4xUraeXpn/zhFimYFCuFqA2xo+8eqP+T43ATg+u1cJ2Y77rnl1s7hMXUJ17kvCgcxTfvxw7k2rP+kMNnLDg+6U5wkQ4i6QinnSMVZxz/xP6C2TNNE7dKMFrgWgU+ulX93daGQRn1mKGKDsei9sKE9ugUFdNyiP8YYPy/bHiBydJIQkwTv8gcKUhNbMyXSFBgjZA6WQXXBTyGwigtEgSkJh7SekbRN2azGT+u5e6AKuEsUtYlhAASnFTMlMgLlweNUmmYFXzQvnshN2TthKTN/Na+0A+s6A3/Wtpgu0taABAwKXqn2EWdbb1yuTT2B6GC2RCFnWfAxhQTw93WpjCG+rCx+FzMN0sVt11JPik4B+NK1amTEkz/zyAvnTzZ3Q4lJrpfV7l1JekxAB
  template:
    metadata:
      name: vm-backup-s3
      namespace: monitoring
