---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vm-backup-s3
  namespace: monitoring
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAjIHhRR1ssdDcmPqqo67qOwkm63JKrpYnsDuv6bfw7SSon1dneQI1S5kPf2wG9ktBs2bI2m/mtnmnmdYyRlq4t7Hqs9Rx4Nd7GCw1aQncIuoEBBFa6XrkOIF4N/w+KTZtk4sslhSGzkjUVccrXVhKicubYdXVU5LaMCYPhF0XySur/QnlfCQ44MtRVLb08Y2qrZcv5FC29pojfNw7ybn1QKNQwtzCkxlDVzMLG6aoKdNTauAfA4xbLshCtr2kDmVjx9sm72w3tMxPsB01E/Fs8HiYpuwuqanpAYHlAcE8mbBNMMk/3WkQSxJ5GsczGmEZ4xwDNn27EPWFlk62VGpqzxSKWHdKOk0ZSTFIXoWlCpbs8ewtYwRRKdsbtJHUrywCcvZv4VymkldSMXcMdH4DhGlxS4ojR48FPbYapWbP72snAxiDzo//RvJnW5Xe1Yds3dnc6lhRYBHDtiaY3qJPKw0GiSRq5AviWMJW07NkyG427djOMbFulWyY75Ze9rr1q1sZKBj4GguznLLzjjlyyaNnhg3GLLSliBXfxlMoHikrUlRoaaiLpNkJlcHOjabTUErbiFHZwQtBGy426oroAY1NA8dBej1LrCSX3uVLnioWAXGqrSQcOGTsySaqfjlUxtib1VUUdQqySCZUkZa5gghDcljM24C+UiTYt2BJ7vik8LSlz2w/C61Fpj2kkfC1KC5oPHTqriozqHyQVQFxobRghqw==
    AWS_SECRET_ACCESS_KEY: AgCoJsJ51IDd61DVW8zLCnv1SVnu8bnRGgJOHxTSfObzQ5sfEsIpEVzoJNA2GFwGxK7n1G5pO51Go3NYAQt71T6dY8WPlwMD4bSPyC/SWBG9ncZNq9UzAq63RGZoA6GKGUzi7az+cy37EFkTCH1M/Eb78bOF9rI38wqxlxu6g8B8KeZCG5iscnKQi69HlmMBOtLpE9w6TGHU7emiLLFNZnd1JZvBjtrOOvEg+Wbr8VsPtBp4HwwrmJdLWGpDPJoJ5e/dbC4wkpJbvy86AxMWAQ+iic9voQ2wDgzxNLh6oOZ4LyJl7c36qA4EIp6jrvywocmd+/eRQa27W6VebjlfVihFjGsfRzqXJJi9/CoYBO6kU4P2N+0vRs172wpRR5mPni+l87TTIWBeUV2rJN5tVJ/EyqpwHeJKThX8quZKqrcc+DTETimkpRGjb2Plx6BumYa6pAi0Msp9VwsSSQQen4TC8EqQzs5OhW+AYv9nrX9ggaDnBfFLpaioVpsjokLzzi2C3Kkw1zq1EFBpmGLXa0eYQsXmx48Zf3iDO1qH6uF85Hi4NvWRkZl8q+TD+mIvt6fKUBDdF1UM6i25sGRV36X52lAT6lIQfPBuVbkxTxMscymGtm4kYssDfeei3qKklGpnNqfDWHxfKqOtL6RNCN8lYH1VYVFH9RUkUVPqql0CxLLLEEy7vVgfQNW5U7JDe166suK0wuekRz3f1AMzwX03i+mHMkgLI0EjHXCfFUwTDWO+or6R0+kx
  template:
    metadata:
      name: vm-backup-s3
      namespace: monitoring
