---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
spec:
  encryptedData:
    password: AgAtrXwbBBJPVRoPrpVv9uWzmqGtUbKKCC3lSOnSEi3da1lx6UUADgQU0SDsbsNg1n/RsiBmzZfiJ9vWkJ5thZs+jn7dKippSOmYeEGFZ/BOdKq7fPM//SeobNsUljv5f8IPSDEsgOA0bsVwIloJFMoTMi01uTA3QDCqnbI81q4WBYO4i/SKNODyE9n4C6ddq5P0v7xvnTMPKmoT+FnvOiDLoVIvx6kNpoM3jIMoKAA4znQ5Wo0EC6OKRnptpu2igF6paxN7JSbNztfSerwS8XffdpmbTQJRUT1O7q4h2/TiSn/06X+luUpdAu82Zzp+iWhtYM58ghgzOma8BX0f9QrsT+0RAQgGswK/SR26CKHiUzvFgAUzEWkzSDIciHgOOWjHZFiwBFV8Z46OyiwSsHMn3DIJOdOPI/SBqUNNH3nMvQ6YeH/mOI0ihmZ8dK1LtmZ5aOUIaw34wJGNcdr3jl19Pv4NoPpFQe1ixa0noaMg4pOlv9jmN5nhETItDJz6QqZcbwZ/51QqLyXqnyMMCIQAk70swg07M6cLl9rX8BRwjVBG0R+Q5qWfPwoDTcvUxoOOLZXDRf2Y/AplhME4FS2UHsH4aM0uGKxB+JEMiUYWTNOjVEN9dCJC+zFpzYmSAS9hDt9HJJYRFyPSgC52SSNOMYE9fNxUb9SbYxgmZHHfgyqduxrjc0Tlc3jMi4ZoKcXnqF3lFwmMKFYa8gJNKttUZ2Jg
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
