---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-backup-s3
  namespace: sample-user-manager
spec:
  encryptedData:
    ACCESS_KEY_ID: AgA3Uo/RYWtszpBaiUF0GS1agEH9KohBHe05Rr+10aBhia1PwRH7a/WjSpZnt83HPEaNH1Yx4l8ARKdXwGaYU6e7PO1dgkKN6BRUO/l6i6jnjp0MaAN4SfVfQ5CeeLJy82bDr7sh496VNBmasMHFAki1DqkrHR/UTaOWYUUeoYKS3w3uLRga4eJjUedIknhlH+CpQas/HYG78IRjzExdyFqndf/k54in6PN2FG5wm8de8/Boleg1kSPT3N3DY1r3ID5/qYylZJKMSX5UeniKMAyhFVDe445fEKk5UhZny6NJ1tbF8ZSEY0G0aHs1BCEfPSd08IkH5jQGfj2iqRAnruwrEADW+mxSNvQG40mYYqbKwheWHcF6UOf9LDKU07Tz+V7ohxDA+vOWKAPzz0AI54+KIQVPKdBzdEX4hpkdYKmuIpZnrWjXDEPmvAC9uSQ5zaks9N1x69LlqNpeZuybbapsqD5GrzDm8wFzU66faBIqIqUx8iW+bq7IRbl0cJ4LCuTJWw1HT0f+Un25XsEFJsmHGMZ0DzVrIZ4rI8f+KdyiVbo0wvv8QmzdqoUEslDGfJvhBGFeGOnP+27Aijlx9irlNm9mvfusE9MXbTOqgEm06cmj6iVUe3lMKLuqkmw2FELYRhFrbmqs6Ua2xnTkjSGbZmt3nPuNrIJNNQMYwB2tD8rPI//txA36ipK2cmevy5GGscvw79ENUi2ZAE0cBToB3x/Hyw==
    ACCESS_SECRET_KEY: AgBCDgcVOpdTYHf1GUEmbsZrk3lUj38QH0rV/s/VGqEo7G0tF7u+ebOrnltFRWKh8WPbw5GE2FnrvwcqxmLi5EWDV4rpse/hxbmYzcwExHvkieaGtfBrG73z1TVjIwyD8UYj7oO3cwoOqD82VqzIbREjh8wHunEb5uJe7rIZjnEPek3vN7qZEIPnuQFCUQBFo3F8knQL6660VOWsXhv9jHkGYuFov/9BNJ/ZDAdU12q63AhIC+zJZGSbHcIsXUnI3pOvoH21l/7K+nkJgCY/GSRuuY4BgleWWe1UbLRi+74lI/j38GfcSLjro9u637GzxXun3DWOjFOsnXsVZBihPzb5CZ3+EF18Int0ZT9zaeqv9Vv/tSpCwdUg0RUQu713GE8C+Xh3l+qXoCQwQiTdCil0C5yCOjl5PzthdXL3xu/xjhO+lDYTSqmAL2anmfjHbunKTy6SIoM2lw3eUGwP5o1gI6zGDX7xPqGHRUUXY7J6JXE5mGgk5yvcThvSEFnDC18N8A+Y3kxdrrtzoZoTPyxDMD6GoyIVCY3DiBDAtzbWm3RpP/znS0oNr3LEVdaUcmf3auL19SbpU9OYX7Lbq43IEVIwOPeDsw5K61UAWrv6dbH/tWD4yj86pRGtWHGk5Xv8SJN2mzfbTN08hsmX4oIu+SEe7a5poHK9o4QyIekePPUpHgVSqaQZ7mtyvtPbJOsFbz4LVofVWF0UepVTzL0LyP3HtugN9IfXbik4Umm8ugR6F8LAd5Q5
  template:
    metadata:
      name: cnpg-backup-s3
      namespace: sample-user-manager
