---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-oauth
  namespace: gateway
spec:
  encryptedData:
    client-secret: AgBP7z1KhS7/bdP8wGadrbVqKnyySohegNNn2r2LVIb4BKQqzNm0M7qV9wqvNuDHgmg+C2JOCnIvq27twHQSLO5yZ7e5G7iJOhAEe6IqGZzD0q72HIzVeH5PIWxsZxKYn00/rBCh1e1WBHsW1alSuCBBzaZxy04alnJcxGg45yCL2RhN2XAgdRIZDx3q/kkq7wTRJiviDtd5B9sf1yJK9MdrO3e4F3W1aN8o+wS7R0wyGnO/1O5LoZoOkQ32A4JeZ2fPCIrFgVyRf7Zp2XsBvCRrT1sz8TTiehiPVKqFB8gAhEAUE8XcnRu38j/7LmbHmfjVF3hpMaf4AK9hT1ab/a+fX9tRbRJCAg2dicPR6Ih1TUiEAIwOV3SRDxIlut95dZtumg3cy2h4TIDmbWwiqVXHsxDaVyu4pmHBXI3W/+Q0FlOsim4SwuphCkrFJrEodq740E4KItiiwsxbr1YEkwh/E1bQYdLO8gGdBVu7Aoc1lIRJLuszlOq1fOEaH1rcnzHRl491VjpEf8JBGhpavRIa+GEVMMw8V0DQZLvGf5kUxEc0QGl9QqEa0aaLqhbr4ajqCxKbdeXpxI8x4VHEuuWgZsc9/OVUDseV6RbDrt5FbfXuK2KEYHo0GwA+j0/YDiahyUBpFSrQEkLzL4gHoBTS2vxsIjuuEIfzfaGtR1kNgLDsOMWWmXgOTpkE3QP+tSxm7eAsQ65yknb7qGNSShhk8kaw+ZfvBxL4ivB1Pi97ayBx4Q==
  template:
    metadata:
      name: google-oauth
      namespace: gateway
