---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-oauth
  namespace: gateway
spec:
  encryptedData:
    client-secret: AgA6UnXJxAq/52prIwQWkKbt4+ZA6fki6y6LeKHCrtr2vhaCA8G+r7pNPTHwSFYV/JKoklR1XLBm2ClZUKoq0hT/sc8FjOTwACWryB1RmShYOpCcbeVfMgfpoWpLka3ff1tqkL96cezuZaj/NY1lz2/0vpqZmOLoLTooMLbpNdHcaB9Avg9hFdr0d3tMdgmxcPF8aR2Yb9jU9liOQtd1RquRasyVg97Bdtp8HxbvDMzhRrWToR3B0CjT3ubFmSl3SpxhXFIgWKDYG80QyixB9m8yp8VrMzCpYj557xSW68i885wA9ll56Wo/TdS64p8SKKmJWbad1slrsLtvixVYS3oHefoNX1AsJoyG5TVfbil/HX7fxmtm88ZD2LVzWEwuxevMSE9XX6Lcskf/If8quRqYMlCztEw1Ogs8Dhe+fkFhnVEpb784qoCELHqRlG91ZijYWvGdgGjQAFS2WRyQF8VKR8R/rzC3SztuW2ta6Gg0uvanRzhYQ+iSX2l420sqn5fW3vk+8LW3NmMnIJYPCBemkf0U9O1rI4JEt7jXKuuxF0ov7ZpEpz2+W1laaDdaEkE351F+MH4UBcZt0vmjx8KUAig2cg/ScLY2LmzcTf3DGP8Iu9rQZSzKgf/11LUQAi3pD0deBrs1HvKVJ85hokFi9Hgdp+W6680orRP7eq5ocpaIqefBK2mVmi3ltRN/YtLLPDo3ZdIN7O07i49bwck6uHzZn8U2Vs1MDlG+Ldm5O/p9Vw==
  template:
    metadata:
      name: google-oauth
      namespace: gateway
