---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-oauth
  namespace: gateway
spec:
  encryptedData:
    client-secret: AgBDP9JLMfhy7rMAVd75o6bwILsZP43zizAFjWqf9D4qxfKCZ0rFX1GxJE0N1/rBOrnyKabS9UUchHzUNw/eQroZwV5gKxnES9GUb+FuT1wLLXdaz0LbJxzgnH4Ck+10g/uU3XTCYamcrwYFPwA/aJpoENvg3IMTu974q4ya13HjSGo9hDGvyUDKdF2VIgkFvhlsGaJeW7WUyz/PuXP6wU40cxxJVmr8MDJEowH4qJ5OE6U7NnPUMRfLCfZfzkCShTHhWBz+EdYokynJSrLICqnAIWjjGLtT6CsbjXiS5bpBc4NdoRKAE5jSKG4UgOwCatnxzJzrWkDe9LRNzCGZp7LEnb6vbuODo2T2Vo+weOX+G8vFUfI5Caps8qI0OtKu6J011XOwJhhNHhHWWNRgF5hPDvexS/WLSHu2oBJ9sxa9Ji34fmNubCfOphXPwFiID1g3NFM44vYVZiLgruOlxet6EMXWz8RTRpFnw6YXr0fYNm8IOplzWCzYMJD2cOCddeOVGbxocHSUQRcLxQT69QyVNBf8wKxw0looSM8xlo58ug59Wgb2kBdeM5m42X3nWZFw99Y5RTVo6f9UvX+TgRRRWv39Gk+f8eUxlnq/NfeClkfEgT81+erWV55VxtPg9MxWKWH/ciVklZlI/dLtpaC99WWCc6jYVjT2bGvd3RBazSor254wuf7iWCOSg9rRDNOIPMH7fUNXwc+Okto1Z9vDK4GtgYDTWcf8vc3IRUYY4CNScA==
  template:
    metadata:
      name: google-oauth
      namespace: gateway
