---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-oauth
  namespace: gateway
spec:
  encryptedData:
    client-secret: AgA2CMyMXD9ovBH9dR0gTgxOjzlWeoyBWTA2uzURr3c6iK/c+xG7UWtOnUMYfZYH5cORdNkFAMU9aPJch+vmzh/w8arPBxipCEgoZ12aZbJHkyh+aLPHu61tyfPDWdxMAWGJd66w2mi32P74/ABOV1hQK3ycG7eg/IZqcf/qz3tBVrTOKdPeG23EaeCnfusnENQ40zHQV8n2vlcmDqv2AR1a6bZJrGCLx7HsBwbyTutlCqrh8858QR4pgSE3zlFnEHqu0g0TI7ykV0o64rJCmw9tnsB4YbNuHnVZ8b/5VjdsSadr7fVxv7qHU30mB0mQq1TUyGjxJIQfMjywwta104wHZb0dAGLTInqP8468+Ae8wvW/2BUM4NcS57h/Y1fu67F9/yi1bJpt6R44gBogF4RhM0ufliCDOun5Vdo2w0zt5IrlJeKwmbnE6sxjaoxZU50iEINOPFGukxhii/Ezu5b/MEwuloSELNEOPHYH3AgZQgTtZQwm3dTXqwS/xYl5FVCc/8L7w/Ay302Yybw8djmufqwXu1wkUpy34HdIhGq5FBQOMg9HA1oXGNZMH8CJlvD7337789QivSVBWNn/vLmQzQ6Pn5x//9ULkk21t0LSoAcq0K2lu4Zv9voDq5keDe4WkFY+R+2r3j48bg2u2Mcjf96PaJjpo2Okuey66IXiAt/8paFkTViEjzIKGWbiFKCmjkHc63M5HN3XdEBQc9TPCZVu96lBwQRZwWMJy//NI0HPXA==
  template:
    metadata:
      name: google-oauth
      namespace: gateway
