---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-oauth
  namespace: gateway
spec:
  encryptedData:
    client-secret: AgCPvMSOu7q8Zs2gdMKbiZ20qLPOVu5mmKMPLA7CUdDrFb7+njm46ueOucO7RNSztlRlNrclTbnmPt307ZWNZlx7dp0POio/3G+OwbbS/3CWNDh4vuP2vCcIv05x8PW/My1A9OAz5Ywo/ElKH1bIHeftEYxI/mhvQl3LuAky63axgGvEANLtAEruPX4Qr1DkkbabZgeq/4rUfApYwIUqMlOb65NRBkmFMevOXswbsImn2SeKxy6GmuKlMNJOEymN7QEE7YiMvwBTXKK2ArnDe7911Mxtutxuwvsaq+09UrV5ACnKJsuFkYtN9scpRZXxYICsUa0TTD5v1bYsEFNbRoUBivuG6He8U2CVYdOloVTifOkkCtOY9v0bmBtq4Je25LvTfmURtcvLiC1R2biS1ju3hOfEUPjDug341nCrsPnb/vM6eFrQTb+uiGNzj/grJ7Tox6WcL43bxBh4nbQEEvCEPNlDL4rWNsAvpHFRshVG9vx+o3LtRXzNBmFv9LEbxhCKnC1hZ1V3CNrHc2eS32QM3YdV8peM2szTq8LoYdnL/5JA6y8KCM/Ses4ZAEIWgofp41+g6Qa/+gI6AqjWWgyjuG1fEXZ7bmsap6IzkK88XUKCQSZB5Dcc5zOWY1tgU1qw4kMfXk1lPNScpMnS5Frnmf+j7TOF21xNLLZfGT7ew2IKuz+ahAgkt1Ss+w4xMdRCRCLBshfMau6j2GFvBudFUf42s8UAw7+r2LyiiFrJ7F5SPg==
  template:
    metadata:
      name: google-oauth
      namespace: gateway
