---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-backup-s3
  namespace: redis-backup
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAoXu2t0izwXct0fZG56pxDtNDZAVNMp+uz+9OoxBA4Ktzl4wTtUtzjvtXMn765QzHkQT9STdmVUDxi3UsXq2qEYEd3dB+LY3feUNqTZT7LCcwdllFs/TBOdhYAjrkGC+ZZQxD7kufJuOhxY6oPAd8OIWtIV/2TLtpNw4liY4bKR038pOuV+4xnPuScCVYN1tiQjvd8xc3Vw7iopFu3pFtgf+FoqOLbHAlC8jiFc5Tn7PsjPZfhdXrmEBxXF5PhnJy02WVTiqN71sLYtkzJYHXY4S5nUEA0NuFdHKf+axZjUyOW94k/pLVQivl6oy4lsENHxEdPWqt1kNFTJQ5H+7kwNrZE/1zcUJ7wijpUe6skz979xfD6tbF/Acde7hZEm4cvI+aBRZNwWlPgN2ZKbaxhmSoQUNCMuDknKyyrBt0hm8lm/ITdgvZ7QR9qe/OWO7YEeGoYe6NQbVq61v02nAee8+fglH71KzYLI2jjrc9V0UlSTPbJ1fDx+cJpAE/dMItH/1K8/Ozzu35a15RAbdIjNUcYY3vwG5WlY+2XiupOS9TtrUHTvP6OrfwGWn7SdLwXGbH4ZjcWO82FECHFLTjH9iVu1GKCrKpofQNHYC3S/ONGhItkRrmSSDLrMhujIWb4ORMUsuAHBSswBqOE+1K7xrwmyzeT/rUtg3ufnOGFLoR1iL7peam8Uj/QFRwXBdoWOp/bzdpewToiEI5I9H9fInfHUA==
    AWS_SECRET_ACCESS_KEY: AgA9s3gBmomwRL3r+pRPTrRDtJFjsW1fcaIFZa+k974TWDiMaOGPJPUaoWH2trairWX6S4GIfcW3ocC8V7nQjYWIWGXCR+bAYN49W7jT8gRiLLpPeGSgv2/O9eoG3apA3oDsAR5UlGln5AvNiTdz7ytiLqTR/1UHhAOfwbLE8e+3jq21Q+NDoAn3GwBziPquQ9L89aRhRvwmvwja6cON+RGGsqr5kazIfOogTpaufHpfS54PE9Dw1sefQeNr7xPBJlSv+zZrJBrNCHqRXaOBDgffKR5OCVbWeDomrm9RIkKcwXWsl4Fy0C80YuLrSxV6EagOmAndoqdoA/YAVK72c57CEj54nudLW+0jFYga3SeCeERrnYm13DiL1F1/i6/tnZUyKmkgk6znMos4FSKHDkvRQxY5u+aK6KOiGgo3/yytXDtvfobGGoMRi1axPpdoTbRqxbsXAcA+MyMOxbfyXrgpf1nDQTB5+1iopwZkQqXkvJrNJiE1ZSILWOzwFEwAC4EupckE99/6fGR9qffNflovXZLIBpUIfRqYKGHnUY9bBoUquQHwf9JR6tg2v8mhTuEIbFffTLpHYzcEsxVsGmJS/BRgx5JLbEhy5Yca9fkWQq8PE4k8YphwPve+8WTig57OODxKO9ya6pcRjcurPnctUZGzqc0Qkl+wJPvrAWG71w9+wJSsoPSK4jBdicdVYPqdXErKbwyiIZVnrt6oPe9sG+O0BCba8fvtDOO03o61dghx5lbhHz0G
  template:
    metadata:
      name: redis-backup-s3
      namespace: redis-backup
