---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-backup-s3
  namespace: redis-backup
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB+5xysElQhOOZ7N58L2n97bZ4wnfTbYh4OmDGR18MXDWKZxDy0aWGdNTjfz/N2yjtKfjYcenwVLtNa/sLRiQy6Uz2L9WEmsC4AZz6GT2xGqm2rYkSGFG2eW1bV1Mlyf9d6iPlyrUwah4YUr/fzRGP7PmYrNtRvyOO9i+RH8jwNd5bpZJHxl7bG4pvHk4ztsfviEGbsOd/ewZH4ijUTKkR309/mCTZdSg3D+/kJyYwvtGSulfOCVrtF7aG0CQMx97pqSkOL8VeOi0bukI086WRGheKfaN4hTwm27IZ7/3a85TOmDNU+jJQO+OzUp7EmsHgRyw2qLxBbASaBgpyh1GmPomq6E/HXiYSkwLafqDy0MwMJghCTnX+BVZPA5GgGMsVEyNVQLxm8m/oM3Qfwcp3RliAa8sCMai2X2s5Q4VN+WiWchsm8rRulGMMzoHAQ6poI+jRstwGkcOGuOD7YmXMh1R5/dRjGnmnCk9J71drZnif6meUz5yl44X5lpJk5A+8oGR/8tksBSdsMNuKYqwfq9K+uV/8qokpvlGpkcTM6R9bsf3hm711EYd6hEVWgLqKXFaepZQaEOHr1MOlthFmQZDSoJXs51VCOvda12HksCXkKl+ZEam7G2oevI0NA88lAecNuCkrlNnBAKcsTXZNjwH+8R7uLQOwsPgLuhq3+EC3NMAgTQK23KPEnCZtJTKwkEIIE4blqjRDvRAoFyfCI52z/eA==
    AWS_SECRET_ACCESS_KEY: AgBhkuu9Sb4fGn8SWCCicju8Z8DO6RlWemnt9V6ujMkuDK88xuvXv1r9DFy4lFccWAUs3Ax9CL8UotO2KZuOUGbyoCVVUHKHKn+XIX+wgzWTe9ajNZb5ZDhsurg+zu0/nrvDCcx+WCCI2u5ZsCwi8opjtSPEK+874g5k67adxk4SE1aA9QErHs1oXQyMPNOUCf28aBdIq1GgU4CkNzF+cw0jfDF1YQ/h7BO8eeqzwnooGiLzYEdw08xw10kylEvKUydADe4bjHsFrFTtUeNwuYl8Z474qcteFnsoOzWYPlStQIro4T10W1n9YjXW+FMIXmbFqxetAurocBW3Sk548BtgAHFnMXuNkApN91mdu7z84vI13//t4nZJm1OQEWAIpAnKHXTA90KBkoxiK4zCvpFeOvGNkak+PHBCpWpjOYU/K3Yiwfuozf2A02qv6YD6C3wSVJPsa5ZYOB/Zup4eyryFKhygQHr5OKVx3FBP2cZRKykQ0+5ACFln96+kp9YsXXUiwRsXr4huQLhlmkWRx2yMcEmI7Ache6NjSb3LizbKQPErvTyE/GJovm5BeNcfgu+DRT7BwUXjohgO12MiM/C6adMWXyJOe5dlctkWEcQwI0CFM9WgWAOnaTpzrNWLmWtR/R6LmC4Jxc4PU4abfSKieKt28/zM3euIyH+2ISNb4N5nRCASSH/DE04nbFwqVsUiKPWFZ/BxFRi1kPU229GWQCfVTVBiGGTMlvn/KL9gdZhbRCy69po1
  template:
    metadata:
      name: redis-backup-s3
      namespace: redis-backup
