---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-backup-s3
  namespace: redis-backup
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCl5MFSYTx0ElASzF/kT2RaCU95WQb1a5GhZm/cpWOpL/TNGM89XGk57hghWa8RDErqgPSOyCCGwnk6/Q04TYeMKkIJcDBrBLvBiVJzjbPR22h0oafnRHxtTz4FKpWMR5EvFiF2+Wt5P8EoJiTLQifYLbhiYV/OL50AU7XMEiZKZuU9kderTypWCRXuif7VFw9OeY35mSsXrxJwHXX1yeZlIAcPNCfQLVIc7qkz9grY4NpSs95nH05XhlwN9BnG31JpBV8q8stVMZM6IbWFOiIPueypGY+WR9mweac6oLmxnP3I26K/4ShUAwQ4kHNcgPtJZWZJuBD8huuO88ZKnwJnvKZ+4wyhu3IKFca23cNopI89vGIqOJiLfZBaNSi+zFWdjKsjOBNboOmqi+pto+Esb4c1fDSLm83OcCo282CVrf7iYH0THFkhbhbegO6YeUfdvwF9iNSWD2wGxaEJOpWntJ0lmB5t69SxTTr+l4knwuSFKFrlhscAKYAGx08ysldOgXW6Az65zrd0j46tz3m3Foe1+NOdRueCPBLeI1WrJv34O6oGvvJwx2/AS3qBIBncEfSHeuo9k4BFFyoGcQbtBoYTzcvXIP+248TOhL3zL3+ugEp6Mn/UhSH3Jdhj/TetSYn+SxjxSkqm3N7MxFIFbfrGCCT7YhK8zX7domWnQqf5bwRd1zifEnnxL8SPi6ozpFsuNRPYKJqrAY+YEyNXVGZClQ==
    AWS_SECRET_ACCESS_KEY: AgCsWDRBujnNsw6wKzkOfAmshb79N1eC+RScGhKMbCY17I5NqJ1Jw0MSWqRm0EE4deeX7qnU07rPB4h619YLvFpfo60k1k3XeCcC0VMIhcak5IpW6hW4ciXqt1O2MQJnmc0nlW3TBfcR9Wauvv41Thmof9Vwyclvp5/13WIfWsJwE1wiLp/MBnOrdzrxVPG3ScbiTCaW08cXAN1ICExePl5kNsvscPG05aUpuUjk32dDA/75n8qrKHy41KiU1CpBaxtAcf0uz7opL/25Ug3DYrQA8IVwR+iRDzG0TO50X5QDanYz8IN8bZMq38cf1r28B/dl99mg4ppiA9GRFTZBAKXzwafgxqRqHx/cMRnsT2UsBq77bc/v2OmFXmX2mRg2P6C35lK3nFOxv60EAPGPRQr0pbJhYEufDHT/BrF7JQUDfKs3WDleBfP8oTA0E1arBx+kEh7IcxanLtpMdp0xj3d76jdKppN8dQYJZEV8Y493G1dvCuWVYJoSyBxCGkIZHDX/vCO9z3doUBgHtChxIGDiY9yH2CfQxg+99MhYldxC5LhXoe5LUVWjlLQRbiLrUAs036sjRQYXllrDfyIAK2BAgKyWJgcRM9EQx7ztJ16uar5ClQy49/WUInMqhmZJhDCh0Dh2S5umZrRTl/Fe5HA/wEzBzw4cN2QN+mzfHsHYsH/IsjLVFAsRJUIh9u1J7hSmh6gHgPXCssnr14+kp2Vp7fty30ppl/7bv8rxw+81Pb3Df6iq89kE
  template:
    metadata:
      name: redis-backup-s3
      namespace: redis-backup
