---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgANd0LSDJ/kgkLnrGnni7RQxzcjdhWIeSD98ro6alR8X/JlT0ag7pOA8KPMrFumfdUYkYYwFYbfn98sgqle8X+IiXUSZAa1XaFlaDsvRX1qgEi3eCzanrtdPFpYIUZPVbfG5SWVSAg+YhUdSq7Y3rtNJWjox9usQBGbjXSDGL+ESjv8KpAO9hQzKh1NRch4FvzuRHyMSk1l8Yu9pB7ooJ8w2xqfgm4fWaj6SW996TDxjMsN3irwBAIy7QF55cAeYMWcclpZ0sAmZ8RrhyfCqlPG+SkvVxblXcgphQ/zfsiNa1Di3kQfFnTsqx5q70apQGirBttWRR3BDykjcxsiBlLWTmVpyOvhAF6AekjtIHnvtTBTehMQoR+514abU7vefteC2SgYgYTQKf2pJNzpRSXqb6Fy/slDfIdhxNFhuNpjy1zQ9adTdLGPQJd5dJpQ5LFDRONOoU4q8CdsaY7XK143snJ1ardyiv5H8HqnttcFPT7kjQu/JsFpzhbc7Jx9WR1oyszqrt/GX6rEs6k7YgG5NIYAQPDV5SLdDBljReYMZsjX5oSdIoJOdMvIRjndgKAT06GqfIXSy6NNl1bwI1liMNcUqBMdlTuSX6RvBq2dM0zd2z7eDyvZUeQO06BXTerk9+3DTWfiv/UosFRPP6UjNmdtsrm20bmn7bD/a6VjafO7ar8daH0q6F2WcXgdRedcqt++YQWA8oiWyrd+omiU0Y7tX9aYqSpIkzxOPtRFv/TEjiBs8RbyHJGUC2FMWO/2Fj1MgX0=
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
