---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDiBxYZoElD/qPrxxwSKbqTpC7ALStmbYPIJ0OVCqgKbOj3ps5kVZtEVFwakzRqZh3bZ8NPpPLcMeujhMEIC4VGeegvQ9gI0enbnObzn+Wd/jb4H4Ox8NmhvtdFHCPVnt+Y54tjZEDZrqpdlXwhYgmXC0VsOIgvhBt+063hPHy6DwMTcfPZQ2C3ABQZfoRptcYPvEYRPKPui4wt12mW0X2He9b77j1KnHsal0goK9RBT4787IzwIVIrlZPZ9nzxBsWeSR7TTjB1KExR+fHS7EgICR1JXYp6yQhQVQewuSnNihqbcDSGpeaAdixGBshWT/U22xVbRVGqt/VIn3RDyHVnhS8Z4dvP1nOUrn2JU5oizOq7NuBja2CrBip1Xqyabw0v6URit5GpM1Q9H4Et0fEV1S64U29nPgF1rVgDq0mkm59ChFXQxB08By2I68txysQZ88TWWb11Ty+zb/gVGvLMYM1+aDouODDnYjeOgu3zHOBqUCFuqs3NoK+5FjCZqRBqp0cdZwSutwY/Cs/BR3Jzl7VKRTm2Np2YQudOcK2dc1av6Lz14ozAC6GC2nFbBL5aNw79Wxvr+iMLAOkuuteUvKJ00i8qfRGnZ6w+AS7QVEyMG29bR2N2WJg5K50sAVolNujadjD4uUaWHaxtT4a6XRuJbv2wO1P51dDJgPJC10ZYJowyGudmi/90bag5Xcz6gilxJmP3RGd6VyQXExYnVgc3Hl7khW/klRKhIt4EPxCgUCQifBcKxEnSz9DxYmSuVV+Apo8=
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
