---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCIrfAcr0HurRYcvtRcRHsROrglRHEFf4lamEpQI7F+qghbgbryKNaBt6YMTeC89GepWisOsNcYRiqmuAvJOREp1d0I3ksiFX1EcKpg9bOff9b6mPQPXL6miWnsrLK+CuE5xtkei6GSTI7I7mrI6hj2kqDbP7spFZsXfB3URqh7K0fRpbbvc2YIwo7CSbQtd8XxZ8IsDoat0b79S4i3ADPjm/nrQBKIs2fLbew4/7Zee0mFoSMIunBYw934MR5nlZHdk+sgsukhvCL7Vwh+b45dw/j0XDFFbmHK7dKg4O3ZLXBP6q+yLkk9jwklA7s0S/7bK1aMZsnCcABWbFerkVonbOl8KPvonSgToqW8RwSlr+2r9xe0hColzrEeBDTlHyry7gd3WmlF/kbf/wCvBVVHi+P7Z8JG2jWbry4aFUGB8Af84gnJAz2gUCm7LONRiBvxqlWGsqsCsMy1ZP2snmCJEwD/88UQNaLDdX0S7wg7eXV7FCeR3ULenUyQJsjzHBC/NboJ2tS6BwCrbhw/lS/GhvZsqQIA623mnj0umWzFhswRsMhfOQVY1C1S77qBcv3owSayMi9KDdoI/Txkpn0OiUys81hGLfZo9K8IqZdjElJHQMoH7lAmRl91h0/btVjCTlquBhEAYp6PawKB96rhMIYtl5VQjo6vdcG9CITlQ4bUMkZnBA1Lq6+txI9xmCD2XBoS9GY2pVtE425L1MhwG4G5+LUWQBV3vN51Pw5+pPttIByuvuOcfhvg9QN/SEDM5Pc+AA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
