---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-ntfy
  namespace: monitoring
spec:
  encryptedData:
    token: AgBG23crjoM5qlUEQtdLUtX7qV6sNj75CFUbIE+Frm4dOImWuAVJV3k42rQeMvKt8QqQ1hOGySQg5zaveOlYHzD7O4cvv7N2sgoyeWagGJdTVrd22byKialkuiYeNueovPQ2oZYOTJPubLsuOpwgFOKZehGp82qHtbaW1lu6ZSrm01v6F2Oo+sZZYqYyqi9/nxOf5S3dv2W9MZ7s6650akM5zc7kvOQhbAs0PCz2CHyJ44bA9QRzYzFVo7Mu5dPXBEprcLtDBU9aBI1c7CnuOeJSNrTBvteVb5S3QGOT1GskAQ/J90rWoznNFYbV5luMTOTYrNqzOGpZ4nKOczeNp41KYd/13xz7HOwZ4Kz9/lz3/KT+lZ70Mx7blSVULybvnkGGosV8PvCn5V/Cs21J95vDf663gNG8D4iyeXBPyNlRLowj687EOZNEQxS1h6g8pleYyR+5W+3SlzQgkIKFxzXU01OFzZw3XsPolOXlWmcrWDSNImuPwQt8PSjxnqAh8I8gc9/13XK3hmdGSVidgXtdWnfdDU0oiOEa0nRk/a14UsVEvk0oxp+8ae8gYBWM5vT1Pa45gzWMH3Xj5XB0Iq4EoRxkFKz7nKKTeiAeu4wD1Wj+B+mdPZKjdw9IA9O1rneYQQfDwlDs7i+n31uH1mCBOWC7h4j+mP6vLq2xbtoJBjlH4C4Trxz0mVD0Za/lIeWmXSOiU/hnPPGiQgZQxLdeOCx1BNneEf2/SG5O2xa5Mg==
  template:
    metadata:
      name: grafana-ntfy
      namespace: monitoring
