---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-ntfy
  namespace: monitoring
spec:
  encryptedData:
    token: AgBXhPgV/2uO+Nj4Z1V3VxgxtxU3pi4J1roH1LiBUVyEVW/hB3bZijB1XULbIdB8Qrwn0aE/q0Y/T42etKfPuyzv4ABcZ/lTWWYkKiPvHpCkV8wxMwh5yi6pLvhbTQU38nL9mwNSn8ddzIKFsy+FIpaXOEpr8uiujZbA/Ga4emtDqZl1TCXBjiC29SxuE3LMORJ509IvEcHhTP0wYX09b63CU3TolYNZuOLTa8ZHPdubbfZbHqYr4GKAXSH1N7e12krVPBsfXhQNqGkSbZtmfEAlTuJP/VOvcGa+ht2C3b366uJY1Qc596vk2atzW3XlrwZARrlzKu+I/DDjgkLW2Yyk3mXnQwyuVRtn2e5G5U+tnRWPGm4vtho4HUT/wov7uyxiMELtJGhIEivCRHUg9GqCo/6xh14IGo0zIl624CGsN+lk4DkoPug79u1uKpxclSWYjDLYCIl5EjfpwBq5Meax9bHaK7M73J9DvGlX5KQqvjjXQn3k/MoZaJ0YNOCmBFyt3y/Mpj3qq3q5dNx7XgeHp+pSzhLGLX1DkT0vqvCJ9cY+9SILzsJyeUl2G4yTt+aqerl2ej49PwVZWoxHbBCg/Vl16YLAGSdYUZDQaBF0xysJwREjixdsnE3/ZtoOZOuTGeSl2Y/4PCfmBq2RI99dx1ZQcP8Rz7h6wWj2HiJAb7Xbnoatu/0d3p4xU+XY7IE0lDWSkm+WNQUhGK6hgGJH2FmtUHeX2G/oLw/JX1qFLQ==
  template:
    metadata:
      name: grafana-ntfy
      namespace: monitoring
