---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-ntfy
  namespace: monitoring
spec:
  encryptedData:
    token: AgBrOscKqn94cUYTf7D1dfDeo58ML0umMAEYudcafLO2rJKOwdUV7J9oOWJPXKF94cUq9sk8AJtbaisgpGny6L9FwS8/NLA6xsw/NI+fJWbMlr/LyR6t64NWxEeFjo6suQNEXylxYkL5R16Z6/Ufk1DOa/DnosgXEz/j93H7NZ4/4zbKiBSiJWFpwqrAyY2ElcKIaR+kZzO2DdA7UEAmENeUtg1iO6h/VDPhTJ42VNGGE2Y/uB1cZwbXWz73nZ33J4W+lQxowCuwCa1Dwlw4UIMk1D+xVl7jd7iEjf2p0D/TZ6L3+b8b6YkaEPtYnCctQYEMZzzL/FiA8BZj+Yg87SghV30YByH70JWQ0ZQq9SBWnZWeNvUG2CK5X3I/wPtNu6sh4LyXSPBFI5ERYo7X5bINe3mvxFjsQpI6dWjJZcD2A7kt36KhPO+y5HDtM9oeFQWS3lrHE1L2eM05/HO5HkKgOF3imjN+XYlUxkXpvkE/LFA9HRB62wYvANPQSlyAnXWv0ILOuVWhspVr8T0P+Sdf4pNStb2kSk1F6EwskKeYenkEKCHOlC7hHArU7h0jsMVRQ/WTsERN8EcdqoJtRMSvs49Fjacp0UWbDLIUUPzwvZ4EVhbO0w3c0l9Pj/B1UAa7w8fW9EILd6y44PX7/NKt/1J6zPFLcQ4sSXXHzTKEt7A0qEldXXsfy+/HLmoMj5rmX38dVIJC0eGRKWaPLbhC2E8IVXP5d6F4HDj3NXofXQ==
  template:
    metadata:
      name: grafana-ntfy
      namespace: monitoring
