---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB6eipZebaosOyuCDGnM849juywqqtKTBrEnvhzqIfoeFcZMCliWIn0bSJqOcxw+w0eKdGFIGYwghrrs8VFerrsMmK4dF868FSprCQCZ0EsquZsqOO6FCdTzkd2esmHLjIKTtKJunbhyPomNgEV/LkQIa+vvw+72Qn7ANlhdLr2LEFTGcNh0fq0B8q+XZfOrMWhhYruOMHa1gX0Dnl9AjMctZxKBEeCW3E+R/jrJUja3uUU+7Vb7Yoo6Xfb8AgpEbiDbDuDV9JXAB2gqAeMuaqf3WIO6ovJyu2ZBq5KkXSMj2DseYOTTsoMTyRkogWgWGysfcOLNzMPor/aFmDvvAjRJ31G/NkdI9ly+0UL0c04N8tCdl0dIdDITpScCz1+Y9IFTnu1rRENOAN5B7q9CMXnE9MQm0kBDPQMC8T2v7x5NgJwCyMOxriQWPVoCPPtC2ZssYo/q1YbxYCGMquHvXla+B32iH7J6YN/0p5ntTHvffisQ6zmPZmrU8Vy/xmfUU3MXcXbi4xwSa+oNEvWAmjauPFkC6CAkZJMS/s552WMPj3nO+D2+hBO0pMHO3r/Upqoi4Cr+9dtBxjysSuSOGwp46KzcKF4n/mhuTKqL33gTS2Lcm2AQ7o4RjMCcoQfNYd09bJ3iEe1Jv1bX34Dp+pbjaVcl6lS8F7XzlmEvDI0onOO/b40uArrJZEI6AZ/y4nl4IR7DUlFvVqS68EzHHh91gK8oQ==
    AWS_SECRET_ACCESS_KEY: AgBLSzNy03x1JmnbxQtDbLHt4MRwIl7OUDWFZd2NsPt1V7bowsCcZfHbe1m2ppq3pj/ZH/7R7d2SgXQmCet7PhD2jYudGNr7CZYlUJZVkqSu8pnrn7JMiOSrAYp/wrpPUjb9yaEp8kASgdiU0fjnHBVo317zJayUPUbkXlL/OwWa8c9esRLAYO2s6WZf8/VrXAIOpSxBjnm7eVznJNzjIGbsIEVaLzj2V4RufNWFJWZ6w+5Q+up9MT/0A+W/JR1aVLmRFal2uVrne60FFyLcSk+bK4/8gcAs0LzWqKDnw9lYxkyPge8IKlduwsYg9I3V+w5D1ZLLMxaT3hiAf9DsrCQ/yk2usU5LG0rvZ3s8twCalSr8MCe1KCSdGG2osXu948tpXEgqvod/fGAY7xxBvT1N4dgmDVAqB2OB5Q73wcDj+kkBCfSGZUuSw/glGSK2UXHLrraaKFzfpxVRq96aVLrYqgm5RJ+IZmNynW+ejLERKzk9NOeS6IoARdofnLx6m/HQ0ERaNmtRwzHgzm2juXZmiBZaCGaHzSXGnFbzmN5PLHBybMYwKgIhzOREwYFpZKPJCsK8Z5Hb+LyDPZx8GN3I+ejseNy26ELbXY3BGrJGcrXIAmQWyllJuvY7Qvply7miInIVfGQyrc264EIW0n+Gnn5MB5C2e0Zr35UCnJ//0h5TwAvLSFuiG4fG6PorZxcf14cwbhamhmDMW3n29qVpLKKAgXWy2VfGutnx8ZqVrcC6O0kASK9U
  template:
    metadata:
      name: longhorn-backup-s3
      namespace: longhorn-system
