---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDDvU2U2qoBjyDPSxOYSHVOkZBZRfQ0d7dfL/DJ2soTP2crLmqWYCLV0ShFAxMM9rBg5xAmnj+aFviCWIl2f1p5DXAFcGwqZ1clSbn8pFbPzNtOyodxRhyYY9bsPO11qMtIT0xrQCO7bHWI5UKYhDNG1Ue2z6o8oaPiqiku6olS9hSf2UlWsD0pH9naZIKv63ALA9LIObvFTEn9VF2UNeZP54sGPZqm/XGOCUMwfgFfFaY2OyiC4uSvH4podWNZXmbrlhs71qwVekSwgrLP5ZD+gbE/kBYV44qTgfrSJwZn7QM1eQsUg+dSb8m0wnWBKqTs45CTSbUxL51P31eRPUeoC1nQRANnlSPPQNolmOoq64k2PCmlmGr5MfTqOW6hVqs7jkg9emFqfD5QvWvCIggLxpFd2MM+7dZPoFGGsixGefyQ0nvFG7WGLYc5FZx0pAVuXvwfNeV20k0eKDn0VYdD0QEY+fwUzHCl3LHe4j7LY3YAy2Yx8ff6o1CMbIgujknc7tUO6UevHiNCKu5Hl5VLK/dXlXDe6LxtDnLN15V4M/Mnn+WaMZshU4OBX+PJXGIkgQecHDN6pLcZuKm24zBA3WNiD28DCL901F0kz+jhReBpBhaX1xzcEilKFI91fsqtaAGzLffmeODnTeC4c40gRyVA6ogb5q+o9o+ksRpRZRY9EWUxr8W1rJmKZhur2OdDqVaA3cxLO3CNWhDtNUPY8jkAEQ==
    AWS_SECRET_ACCESS_KEY: AgAkgTJZhRVGI9jsPfZKzokeNqnhlf+2lTI6h2Eg0jj2KptnDsoSYlYqciR9OCwcMPp+lPOQkbmxn9IVg31SRFB4RnqN+5tYkknzMT7E5Axd2jepKAAWzhO+EK++fKa3S+fdWCs7cJP8RfWyPjCOon4umvZyPuQCZPkZGggJgkwliFupeTBmN1Ja3oqyfRSW85fFzv05JQUEXwlm8nctVYdzb6i0L05GfLXay/mAOvaTkTNw3J7cXn3pD98cyuXjGeeq/MXWO08NDLtY8xzvkjw89DP2xtkzP4mcRQEsUMuS1KWSsJ6RaJ6IuuanjVuqYyc3SyO8+KJ3KRcohMuuXvPWvn687JjAsyXabziFKfIXPhVKUqw74hTh25z9jgsljmOwTazwgYaKMI6tNmKlONBWLGyWswTrCcgNQ7LKGOnd1FJugo60qnVso1d0yo3IAiSRC4KbxyHcNOfxnQUb3zufKR8CVyIcR5f/r1/XBbQF/cWu9sT6VfVCiFKhe+s3W+sGzpjAbx5Wlh/G7e1MqudSNxOkmMmIdfLQRDvI9KdohyRAc3gX542Cg0pagrYJAbeUzmR+pWNkk284IUK+a+PaNvcASbumtBMMnufygcJP6Yge5wuQ5w1FBzhqtIr/DzsUdVAmG32VV/hXi6JegdBaD4W9MWE/45DaxP04cZJZcB77pCgQhkEnRUPIl+ij1TLeHsWWbUdlz9wcl8LjTHAZBZlqE/PTZ8xHJpAdeeBK9Q3TFQwHFYT1
  template:
    metadata:
      name: longhorn-backup-s3
      namespace: longhorn-system
