---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBhjO3njdHCFGtqFNxdH9hMFH3vnll4YlmlFAOMgll9de6RFaWARqU9oWZYYGiOaujA1El3QRdVHV6cCcleSamRxY9MM8aePWcLoIwp4szrC/jEICrr7zko9FJ9r/bq08AEkvDR3q49yniiKqFh9n4c/wQ7ypRkue4IJCGStfvWuVWSZp2gjnKBA5JjOm48QsJ41z2UnRIT9b+bAB+wQr6TZWAre31gNsryo/W2I9iBTehQFXBliC1VPGRhrJ8Em1WJniBIdCLXht07Eur43zpUma2ysZuQAC9oYPq5cNXv0WnkGDM40MvPd3VPlCm9+JMgbxS5PXVDMaFrsZMaynguoWNrBlWpZPH8bke+k5tamE3fjIIDZvjjHLtg+wNHg8r0PGX4hZkMmmvfBVndtksK9gum7zn5oAxLBE80K00T8sqJ4+QEUIc5d6FhfY8c34Uc2SANDFfJGcWTz2O7DQFDp/KyirPDcQDXB+d503HdBLBMimXb9iBPykdS7v5TkkIaUo+UJqqmPVkHskyWzWd6xQR02RR6nh3JkjEjlZrwZv0DLVsIXQAo2dKXWnzzahqonLQDY4OT49Q5TyPN/PtMynSdILfW10p7ug9VS8pBHglVnxLFDYaCYuh6HPOzxH1LqJLswWJQJPBaCdoek5krKhZTcab6dHtaVvW8RyYNIhbqNsfOPF6LBe46RYTfBbQ1Vmjom7ZkSEC52H8SwJ9h89LaCg==
    AWS_SECRET_ACCESS_KEY: AgBSlQxjQqrBuBFsoBvXThQJ7gRoWRHN5eps3WfvlgVOLaISon9Sv/XYQfjzzNVFcyg4LNmnphTdSZhKb+Z6I9UzbFF67EbS4+geA9zrvhVcH6+ZqK4QBMGnJ/2ZiEx/6J8qV7Y6givZ5wKk4HrYXGNhc3FtzDHry+FeT8OzzhOFQynyR+2H4l45YOMns3qoe0Lx/AHdnNRMi/POOWoIdhFXd8zHgcSFEVmTA2LquSHVR8M68WC/tvrsTE1eYlJY0X7poxK+4MhBuYcce5HjbwTY8dFKrc4Qqo2IIu456xGr0SW5Um7IaSsOavtxHtNpe3y2nXoAmDR/4F0qYTq9O4bD8WaZN5MvlmXIcTNV7WxEG9I6y9mguyCQNGlXOzMO0THAWZ8PTppEYl6vNtC1VHY7KK4q5CjfWWLxUZ1y4S0QaqPOuCd5WxvhUBnD+OroVKkTTIoj7rr3/8wmpkMuC9iKb9upnFLZtayT4Ryyr5HoCqTvrchuZXAtPlFeq/KN9V7qhGqexOZ+WPOu5f8RhlN9C/T0HXrP1/+sCE3/4o8wM3gENxtH71nC6/GCyKPYHfPpiQmnehDMVpVqxv/VSOYkldyQf9ysEemNFPisAS5wr2xKc8rySrE6433Nv/u12OkaejkwyFkaX3isfVmYOTvJ3/R7uuuGF16L/nxAydI1VlUPklhzoFZzXghA31GWUmqFICM2DBf80+TvRR9ciX0/FId9uczPfdUYqBUoOKwm81rOj794NQuJ
  template:
    metadata:
      name: longhorn-backup-s3
      namespace: longhorn-system
