---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgBNEXx4zUclylzCeRxyRuGtIx2EVe/vDmirE8RGvxdu2JK3bLKeAREgHkud+iEWsskiTCx3Eivzl0kaH293M8aEI/gyqN53DeUCgxCWoJ4sgPvraVO/xzeh01EYPV4JLuWzLhmS4a4Ox8jRXhg0ZRcyoK7BnOjHlMPQ+oblaxMvfbdzXaW3ygxN1/aKZCYKxvUiq8yDFTlMYH2LvOimReIIoTkA2DR4h1rwYLYJKUxJFIfLjqS7n3aPUWjTQ5YH/WJl/xF+XJq77hnOB/gp3gItxG2D7PMD3qr0ElXE9mpdQIIIucSNa1w+Q2dincxTObpgFoZj4p/NAN+J6/pOmsnzHlCrj5trMwtmbYnPY+5AqFoE5Uv0V6MFsp5/Iky3iByn/VOWCuF3LyfoZpA9a+GW7q+jp757TpR3XUFwDwkFLmp5KZQKO6+traVWHZMpLRR5d5GcE5+F2t2/WDnhEr+TPCdfTt1ZVluWN+jyby4DIhVUw7tCaClgjNy17E9MRzssb6z5nn595/4AmsV3P/FyiZ1/Lv/sw3Nl3mc54WoUR4XgBWdys1bzZhu//rzzML2J3ZpNnInkmS/QuhBc31dRGacfJpGeJ0IE3zxhKapm4EZ1PjgUII4HWHmGAYT0JSiJ00Hi8fsFMM6+v6RKCf+ieXHXdZIq/9z7BF+M8FG368iZQxuPEcEtVSKKeDmCVnbxAx8REnNEzTx/2XglympFlS2torGMcMQUd0j/shH1VToBQatxqVqitF2UkohomIp2F0xYd7KFNB9ufmVLMeN3
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/part-of: argocd
