---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgBaRr+qZJ9pMfxXbBU4ElEhG85PTthCmoQdmekLhxoo4h+m873CiWNiQIbe56wQArknsHFqvkdeONkXKtSMZ8E7LXUX2pijDhKoDLbLzUXxtx4k6fdpxU0u4OKaXcRN4E9e2IRuBw1JT44PMCmwX5pLAqSFBsZdUfnVrhuGR5qnkR5Jx8mZrwXN5qjzNw6pQMXhy9fR/mnyL+fcGdQYG+NN+YVFQk/2k7BQLdQapq8qt6miTaop9jQAxE5KN9Vcv5MwE2uKw9GAKqlS/INOrlx9EwRSZa4FNMkg0Z6zHhXV98eY1IIAU/LhnlvPqGDMzk6guI8urjFwHKMiK3b6rc6jzIEcwkIzorfBP1m0sPi/aNVJkFRIQ61nQc/D3cwrbsJO/pCsFqZ/WD2tS1EL1EMEgrn6dLLAuN2+BMlsHDKe3sTBPD46oHMO97/tj2mFA5OjWW194c5B7PHx2HIeerVWxhocERlZWmUB4dBN3/1TcgZoSAwLlEBhgI5/idEumgDlfXNitExiZHVhi8eCWtvG8are5by/t2zFpvijLmJrpY+uPieoVD/huD6neCio4UwpUh3Rf7/i9my3OnfP+DHdF6/JWw3+2mB/Fr5RDAxUudq+nlRusZ2o4in/xH9lsSX6f3OaNRqYGxMt9dAjeBYR156rVtaTCGfw2l8/bd9C1WR+C0uu3kO1a+8HiTyqjK7076P7brd6u6BJ2XfaAu5qN0mT+0PL2tZM4Hk9LKtSZrfqiKt5L7q94gw98Lx2NV5nveAd01eb0OW/IplUflyu
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/part-of: argocd
