---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgAmfdHGlIRfWp7QpVAcXNo6i1NhrBPP76cDIDrc80LLfuB/TgHauhrWLDiFYdbXD/kOlh2V+IDvXNHV1yMCYRaNU3xEXDZNJP2w3pNt6+N81XOU/7Vg9RhedQHQ6RGj435hiZjIukhIpBmaSFHXCn2i2xMqLAt8xEnorHC/gGG6S/cHjp0LZu9c0g/QT38rC31lT4NTm+5cAmy3hYv8A3CGX/8ogaj5mhFz5ej72aF50Un0gEVrkiN58m7/TD2sL3xi2YeJ3BItl+Q1L78vQJ4C+r6G74oKDFcxHxu7q6uaMaFdYPd4Tes+u4GMAVGWuMVexkfvgGPF+avP7ghHZ2EW+VFyy30uMu0Vip4CXnkNV93iqWS5DgiSpwVtfaRR5NVkJJQKkU9VCIlt1AqugY0VAAfXoNiPiIgx9/QUxpJnZlK/k+rORGDaIzTszztidSbhSV7fpmmB4WO5cijGMst5yseb4iTsdwdbJlYYGsX3+YxI5jeCDrXFt47MhYni2RlLUQX18+f77OWBGsWYJUrELsqaKIwUTCuL6v+LOVThefQeqpE4ouvjpkEYmxFYZAGxNs5211HVI7XCC7ZoTA4VWw4334kryPniCRDfEc4y0XnvbXs3pkPKpkjJ91tlzXHrnXe9dMRu8Cuwo8H/yHqmRilAbM0nqpodL6ntBvYOVxagGSpz0WIq0qZsZZnhnvIwVGlg2xAqAGDDpH1oMyRbZSGyxqonZi6aNpE14LJICRm/k4F0VdpzhyP77tvlQtR3FungbO0/9WLLLRlfqz4t
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/part-of: argocd
